<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packet.proto

namespace GPBMetadata;

class Packet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xC0\x02\x0A\x0Cpacket.proto\"\x81\x01\x0A\x0ADataPacket\x12\x0C\x0A\x04type\x18\x01 \x01(\x05\x12\x17\x0A\x05login\x18\x02 \x01(\x0B2\x06.LoginH\x00\x12&\x0A\x0Dauth_response\x18\x03 \x01(\x0B2\x0D.AuthResponseH\x00\x12\x19\x0A\x06update\x18\x04 \x01(\x0B2\x07.UpdateH\x00B\x09\x0A\x07payload\"'\x0A\x05Login\x12\x0F\x0A\x07service\x18\x01 \x01(\x09\x12\x0D\x0A\x05token\x18\x02 \x01(\x09\"/\x0A\x0CAuthResponse\x12\x0E\x0A\x06status\x18\x01 \x01(\x05\x12\x0F\x0A\x07message\x18\x02 \x01(\x09\"J\x0A\x06Update\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09\x12\x0C\x0A\x04type\x18\x03 \x01(\x09\x12\x15\x0A\x0Dpersist_cache\x18\x04 \x01(\x08b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

