<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packet.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>DataPacket</code>
 */
class DataPacket extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     */
    protected $type = 0;
    protected $payload;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $type
     *     @type \Login $login
     *     @type \AuthResponse $auth_response
     *     @type \Update $update
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Packet::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->type;
    }

    /**
     * Generated from protobuf field <code>int32 type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkInt32($var);
        $this->type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Login login = 2;</code>
     * @return \Login|null
     */
    public function getLogin()
    {
        return $this->readOneof(2);
    }

    public function hasLogin()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.Login login = 2;</code>
     * @param \Login $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkMessage($var, \Login::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.AuthResponse auth_response = 3;</code>
     * @return \AuthResponse|null
     */
    public function getAuthResponse()
    {
        return $this->readOneof(3);
    }

    public function hasAuthResponse()
    {
        return $this->hasOneof(3);
    }

    /**
     * Generated from protobuf field <code>.AuthResponse auth_response = 3;</code>
     * @param \AuthResponse $var
     * @return $this
     */
    public function setAuthResponse($var)
    {
        GPBUtil::checkMessage($var, \AuthResponse::class);
        $this->writeOneof(3, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Update update = 4;</code>
     * @return \Update|null
     */
    public function getUpdate()
    {
        return $this->readOneof(4);
    }

    public function hasUpdate()
    {
        return $this->hasOneof(4);
    }

    /**
     * Generated from protobuf field <code>.Update update = 4;</code>
     * @param \Update $var
     * @return $this
     */
    public function setUpdate($var)
    {
        GPBUtil::checkMessage($var, \Update::class);
        $this->writeOneof(4, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getPayload()
    {
        return $this->whichOneof("payload");
    }

}

